sudo: required

language: python

python:
  - "3.7"

install:
  - pip install docker

services:
  - docker

script:
  - bash scripts/test.sh

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
